Vagrant.configure("2") do |config|
	config.vm.define :master do |master|
		master.vm.box = 'bento/ubuntu-16.04'
		master.vm.provider "virtualbox" do |v|
		  v.name = "git-m2"
		  v.customize ["modifyvm", :id, "--memory", "256"]
		end
		master.vm.network :private_network, ip: "192.168.2.22"
		master.vm.hostname = "git-m2"
	end
end