Vagrant.configure("2") do |config|
	config.vm.define :master do |master|
		master.vm.box = "ubuntu/xenial64"
		master.vm.box_check_update = false
		master.vm.provider "virtualbox" do |v|
		  v.name = "git-m1"
		  v.customize ["modifyvm", :id, "--memory", "256"]
		end
		master.vm.network :private_network, ip: "192.168.2.21"
		master.vm.hostname = "git-m1"
	end
end